# Generated by Django 6.0.4 on 2026-05-26 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('cpf', models.BigIntegerField()),
                ('matricula', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('data_de_nascimento', models.DateField()),
                ('curso', models.CharField(max_length=255)),
                ('periodo', models.IntegerField()),
                ('turma', models.CharField(max_length=255)),
                ('ingresso', models.DateField()),
                ('nota', models.FloatField()),
                ('telefone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('pai', models.CharField(max_length=255)),
                ('mae', models.CharField(max_length=255)),
                ('telefone_responsavel', models.CharField(max_length=255)),
                ('email_responsavel', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('cpf', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('funcao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('cpf', models.BigIntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('matricula', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_de_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaProfessor',
            fields=[
                ('cpf', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.checklist')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laudo', models.CharField(max_length=255)),
                ('texto', models.TextField()),
                ('ano_diagnostico', models.IntegerField()),
                ('atendimento_fora_da_escola', models.CharField()),
                ('texto_atendimento', models.TextField()),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoPedagogica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField()),
                ('descricao', models.TextField()),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='FuncionarioEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='HabilidadeAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente_curricular', models.TextField()),
                ('habilidade', models.TextField()),
                ('facilidade_dificuldade', models.TextField()),
                ('metas_turma', models.TextField()),
                ('metas_especifica', models.TextField()),
                ('procedimento_metodologico', models.TextField()),
                ('avaliacao', models.TextField()),
                ('adataptacao_curricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.checklistpergunta')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesse', models.TextField()),
                ('habilidade', models.TextField()),
                ('nao_gosta', models.TextField()),
                ('dificuldade', models.TextField()),
                ('informacao', models.TextField()),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistPerguntaTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.checklist')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='Planejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidade', models.TextField()),
                ('metas_curto_prazo', models.TextField()),
                ('metas_medio_prazo', models.TextField()),
                ('metas_longo_prazo', models.TextField()),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='PEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.DateField()),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.professor')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPedagogico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.professor')),
            ],
        ),
    ]
