# Generated by Django 6.0.4 on 2026-06-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoescolar',
            name='texto2',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
