# Generated by Django 6.0.4 on 2026-06-09 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0002_historicoescolar_texto2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habilidadeacademica',
            old_name='adataptacao_curricular',
            new_name='adaptacao_curricular',
        ),
    ]
