# Generated by Django 6.0.4 on 2026-06-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0003_rename_adataptacao_curricular_habilidadeacademica_adaptacao_curricular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidadeacademica',
            name='adaptacao_curricular',
            field=models.TextField(),
        ),
    ]
