# Generated by Django 6.0.4 on 2026-06-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0004_alter_habilidadeacademica_adaptacao_curricular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistperguntatexto',
            name='pergunta',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='ChecklistPergunta',
        ),
        migrations.DeleteModel(
            name='Pergunta',
        ),
    ]
