# Generated by Django 6.0.4 on 2026-06-17 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0005_alter_checklistperguntatexto_pergunta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='tipo',
        ),
        migrations.AddField(
            model_name='checklist',
            name='checklist',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='estudante',
            field=models.ForeignKey(default=123456789, on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='pergunta',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='texto',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChecklistPerguntaTexto',
        ),
    ]
